interface Team {
  [index: string]: {
    teamName: string,
    code: string,
    flag: string,
    pot: 1 | 2 | 3 | 4;
    bbcName?: string;
  }
}

export const TEAMS: Team = {
  ALG: { teamName: 'Algeria', code: 'ALG', flag: '🇩🇿', pot: 3 },
  ARG: { teamName: 'Argentina', code: 'ARG', flag: '🇦🇷', pot: 1 },
  AUS: { teamName: 'Australia', code: 'AUS', flag: '🇦🇺', pot: 2 },
  AUT: { teamName: 'Austria', code: 'AUT', flag: '🇦🇹', pot: 2 },
  BEL: { teamName: 'Belgium', code: 'BEL', flag: '🇧🇪', pot: 1 },
  BIH: { teamName: 'Bosnia and Herzegovina', code: 'BIH', flag: '🇧🇦', pot: 4, bbcName: 'Bosnia-Herzegovina' },
  BRA: { teamName: 'Brazil', code: 'BRA', flag: '🇧🇷', pot: 1 },
  CAN: { teamName: 'Canada', code: 'CAN', flag: '🇨🇦', pot: 3 },
  CIV: { teamName: 'Ivory Coast', code: 'CIV', flag: '🇨🇮', pot: 3 },
  COD: { teamName: 'DR Congo', code: 'COD', flag: '🇨🇩', pot: 4, bbcName: 'Congo DR' },
  COL: { teamName: 'Colombia', code: 'COL', flag: '🇨🇴', pot: 1 },
  CPV: { teamName: 'Cape Verde', code: 'CPV', flag: '🇨🇻', pot: 4 },
  CRO: { teamName: 'Croatia', code: 'CRO', flag: '🇭🇷', pot: 1 },
  CUW: { teamName: 'Curaçao', code: 'CUW', flag: '🇨🇼', pot: 4 },
  CZE: { teamName: 'Czech Republic', code: 'CZE', flag: '🇨🇿', pot: 4 },
  ECU: { teamName: 'Ecuador', code: 'ECU', flag: '🇪🇨', pot: 2 },
  EGY: { teamName: 'Egypt', code: 'EGY', flag: '🇪🇬', pot: 3 },
  ENG: { teamName: 'England', code: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', pot: 1 },
  ESP: { teamName: 'Spain', code: 'ESP', flag: '🇪🇸', pot: 1 },
  FRA: { teamName: 'France', code: 'FRA', flag: '🇫🇷', pot: 1 },
  GER: { teamName: 'Germany', code: 'GER', flag: '🇩🇪', pot: 1 },
  GHA: { teamName: 'Ghana', code: 'GHA', flag: '🇬🇭', pot: 4 },
  HAI: { teamName: 'Haiti', code: 'HAI', flag: '🇭🇹', pot: 4 },
  IRN: { teamName: 'Iran', code: 'IRN', flag: '🇮🇷', pot: 2 },
  IRQ: { teamName: 'Iraq', code: 'IRQ', flag: '🇮🇶', pot: 4 },
  JOR: { teamName: 'Jordan', code: 'JOR', flag: '🇯🇴', pot: 4 },
  JPN: { teamName: 'Japan', code: 'JPN', flag: '🇯🇵', pot: 2 },
  KOR: { teamName: 'South Korea', code: 'KOR', flag: '🇰🇷', pot: 2 },
  KSA: { teamName: 'Saudi Arabia', code: 'KSA', flag: '🇸🇦', pot: 3 },
  MAR: { teamName: 'Morocco', code: 'MAR', flag: '🇲🇦', pot: 1 },
  MEX: { teamName: 'Mexico', code: 'MEX', flag: '🇲🇽', pot: 2 },
  NED: { teamName: 'Netherlands', code: 'NED', flag: '🇳🇱', pot: 1 },
  NOR: { teamName: 'Norway', code: 'NOR', flag: '🇳🇴', pot: 2 },
  NZL: { teamName: 'New Zealand', code: 'NZL', flag: '🇳🇿', pot: 4 },
  PAN: { teamName: 'Panama', code: 'PAN', flag: '🇵🇦', pot: 3 },
  PAR: { teamName: 'Paraguay', code: 'PAR', flag: '🇵🇾', pot: 3 },
  POR: { teamName: 'Portugal', code: 'POR', flag: '🇵🇹', pot: 1 },
  QAT: { teamName: 'Qatar', code: 'QAT', flag: '🇶🇦', pot: 3 },
  RSA: { teamName: 'South Africa', code: 'RSA', flag: '🇿🇦', pot: 3 },
  SCO: { teamName: 'Scotland', code: 'SCO', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', pot: 3 },
  SEN: { teamName: 'Senegal', code: 'SEN', flag: '🇸🇳', pot: 2 },
  SUI: { teamName: 'Switzerland', code: 'SUI', flag: '🇨🇭', pot: 2 },
  SWE: { teamName: 'Sweden', code: 'SWE', flag: '🇸🇪', pot: 4 },
  TUN: { teamName: 'Tunisia', code: 'TUN', flag: '🇹🇳', pot: 3 },
  TUR: { teamName: 'Turkey', code: 'TUR', flag: '🇹🇷', pot: 4 },
  URU: { teamName: 'Uruguay', code: 'URU', flag: '🇺🇾', pot: 2 },
  USA: { teamName: 'United States', code: 'USA', flag: '🇺🇸', pot: 2 },
  UZB: { teamName: 'Uzbekistan', code: 'UZB', flag: '🇺🇿', pot: 3 },
};
