export const TEAMS = {
  ALG: { teamName: 'Algeria', code: 'ALG', flag: '🇩🇿' },
  ARG: { teamName: 'Argentina', code: 'ARG', flag: '🇦🇷' },
  AUS: { teamName: 'Australia', code: 'AUS', flag: '🇦🇺' },
  AUT: { teamName: 'Austria', code: 'AUT', flag: '🇦🇹' },
  BEL: { teamName: 'Belgium', code: 'BEL', flag: '🇧🇪' },
  BIH: { teamName: 'Bosnia and Herzegovina', code: 'BIH', flag: '🇧🇦' },
  BRA: { teamName: 'Brazil', code: 'BRA', flag: '🇧🇷' },
  CAN: { teamName: 'Canada', code: 'CAN', flag: '🇨🇦' },
  CIV: { teamName: 'Ivory Coast', code: 'CIV', flag: '🇨🇮' },
  COD: { teamName: 'DR Congo', code: 'COD', flag: '🇨🇩' },
  COL: { teamName: 'Colombia', code: 'COL', flag: '🇨🇴' },
  CPV: { teamName: 'Cape Verde', code: 'CPV', flag: '🇨🇻' },
  CRO: { teamName: 'Croatia', code: 'CRO', flag: '🇭🇷' },
  CUW: { teamName: 'Curaçao', code: 'CUW', flag: '🇨🇼' },
  CZE: { teamName: 'Czech Republic', code: 'CZE', flag: '🇨🇿' },
  ECU: { teamName: 'Ecuador', code: 'ECU', flag: '🇪🇨' },
  EGY: { teamName: 'Egypt', code: 'EGY', flag: '🇪🇬' },
  ENG: { teamName: 'England', code: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  ESP: { teamName: 'Spain', code: 'ESP', flag: '🇪🇸' },
  FRA: { teamName: 'France', code: 'FRA', flag: '🇫🇷' },
  GER: { teamName: 'Germany', code: 'GER', flag: '🇩🇪' },
  GHA: { teamName: 'Ghana', code: 'GHA', flag: '🇬🇭' },
  HAI: { teamName: 'Haiti', code: 'HAI', flag: '🇭🇹' },
  IRN: { teamName: 'Iran', code: 'IRN', flag: '🇮🇷' },
  IRQ: { teamName: 'Iraq', code: 'IRQ', flag: '🇮🇶' },
  JOR: { teamName: 'Jordan', code: 'JOR', flag: '🇯🇴' },
  JPN: { teamName: 'Japan', code: 'JPN', flag: '🇯🇵' },
  KOR: { teamName: 'South Korea', code: 'KOR', flag: '🇰🇷' },
  KSA: { teamName: 'Saudi Arabia', code: 'KSA', flag: '🇸🇦' },
  MAR: { teamName: 'Morocco', code: 'MAR', flag: '🇲🇦' },
  MEX: { teamName: 'Mexico', code: 'MEX', flag: '🇲🇽' },
  NED: { teamName: 'Netherlands', code: 'NED', flag: '🇳🇱' },
  NOR: { teamName: 'Norway', code: 'NOR', flag: '🇳🇴' },
  NZL: { teamName: 'New Zealand', code: 'NZL', flag: '🇳🇿' },
  PAN: { teamName: 'Panama', code: 'PAN', flag: '🇵🇦' },
  PAR: { teamName: 'Paraguay', code: 'PAR', flag: '🇵🇾' },
  POR: { teamName: 'Portugal', code: 'POR', flag: '🇵🇹' },
  QAT: { teamName: 'Qatar', code: 'QAT', flag: '🇶🇦' },
  RSA: { teamName: 'South Africa', code: 'RSA', flag: '🇿🇦' },
  SCO: { teamName: 'Scotland', code: 'SCO', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿' },
  SEN: { teamName: 'Senegal', code: 'SEN', flag: '🇸🇳' },
  SUI: { teamName: 'Switzerland', code: 'SUI', flag: '🇨🇭' },
  SWE: { teamName: 'Sweden', code: 'SWE', flag: '🇸🇪' },
  TUN: { teamName: 'Tunisia', code: 'TUN', flag: '🇹🇳' },
  TUR: { teamName: 'Turkey', code: 'TUR', flag: '🇹🇷' },
  URU: { teamName: 'Uruguay', code: 'URU', flag: '🇺🇾' },
  USA: { teamName: 'United States', code: 'USA', flag: '🇺🇸' },
  UZB: { teamName: 'Uzbekistan', code: 'UZB', flag: '🇺🇿' },
};
